[package]
name = "duckling"
version = "0.1.0"
description = "duckling"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "lib"
path = "src/lib/mod.rs"
crate-type = ["lib", "staticlib", "cdylib"]

[build-dependencies]
tauri-build = { version = "2.0.1", features = [] }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
arrow = { version = "54.1.0", features = ["prettyprint", "csv"] }

duckdb = { version = "1.2.1", features = [
    # "modern-full",
    # "extensions-full",
    "bundled"
] }

futures-util = "0.3"
rust_decimal = { version = "1", features = ["db-tokio-postgres"] }
tauri = { version = "2.2.5", features = [
    "devtools",
    "image-ico",
    "image-png",
    "tray-icon",
] }
# tauri plugin
tauri-plugin-shell = "2.2.0"
tauri-plugin-dialog = "2.2.0"
tauri-plugin-log = "2.2.1"
tauri-plugin-process = "2.2.0"
tauri-plugin-window-state = "2.2.1"
tauri-plugin-clipboard-manager = "2.2.1"
tauri-plugin-store = "2.2.0"

anyhow = "1"
url = "^2.5.0"
log = "^0.4"
nanoid = "0.4.0"
chrono = "^0.4"
chrono-tz = "^0.8"
async-trait = "^0.1"
time = "0.3.34"
uuid = { version = "1.7.0", features = ["v4"] }
tokio = { version = "1.36.0", features = ["macros", "test-util"] }
sqlparser = { version = "0.53.0", features = ["json_example"] }
sqlformat = "0.3.5"
glob = "*"
regex = "1.10.4"

[target."cfg(not(any(target_os = \"android\", target_os = \"ios\")))".dependencies]
tauri-plugin-updater = "2.6.1"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
